### ISSUE TITLE
Can't specify both reference (which does not equal 'master') and tag in puppetfile. 

### ISSUE THREAD

**Issue by jjarokergc** [adrienthebo/r10k#1250]
## Describe the Bug
r10k does not appear to work in a main branch that is labeled something other than 'master' when a tag of that branch is desired.

## Expected Behavior
It should be possible to specify a tag of an arbitrarily-named branch, such as
```
mod 'jupyterhub', 
  :git => 'git@github.com:ComputeCanada/puppet-jupyterhub.git',
  :ref => 'main',
  :tag => '3.8.9'
```

## Steps to Reproduce
Select a git repo that has a branch named something other than "master".  For example, ComputeCanada/puppet-jupyterhub.git names their branch 'main'.  The following specification fails when a tag of this branch is requrested:
```
mod 'jupyterhub', 
  :git => 'git@github.com:ComputeCanada/puppet-jupyterhub.git',
  :tag => '3.8.9'
```
The error message is:
```
root@puppet:/etc/puppetlabs/code/environments/production# r10k deploy environment -p
ERROR    -> Error during concurrent deploy of a module: Unable to manage Puppetfile content 'jupyterhub': Could not resolve desired ref '3.8.9' and no default provided
ERROR    -> Unable to manage Puppetfile content 'jupyterhub': Could not resolve desired ref '3.8.9' and no default provided
```
When specifying both `ref` and `tag` as in the example at the top, the following error occurs:
```
root@puppet:/etc/puppetlabs/code/environments/production# r10k deploy environment -p
WARN     -> R10K::Module::Git parameters 'ref' and 'tag' conflict. Specify one or the other, but not both
ERROR    -> Error during concurrent deploy of a module: Unable to manage Puppetfile content 'jupyterhub': Could not resolve desired ref '3.8.9' and no default provided
ERROR    -> Unable to manage Puppetfile content 'jupyterhub': Could not resolve desired ref '3.8.9' and no default provided
```

## Environment
 - r10k  10.1.1
 - Puppet 7
 - Ubuntu 20.04

## Additional Context
The only way to deploy this repo was to specify only the `ref`.  The following works, but it is not desirable since the main branch is expected to change.
```
mod 'jupyterhub', 
  :git => 'git@github.com:ComputeCanada/puppet-jupyterhub.git',
  :ref => 'main'
```

**Comment by Magisus** [comment]
In Git, a tag is an arbitrary label for a given, fixed commit. That commit might happen to be part of a certain branch, but the tag doesn't really care what branch it's part of. On the other hand, the branch specifier refers to the current `HEAD` of the branch of that name, which is what r10k looks for with the `branch` option. It's not meaningful to list both, which is why r10k disallows it: either you want it to check out a tag, or you want it to check out the `HEAD` of a branch. While those might sometimes coincide, they mean two very different things.

Looking at that repo, it looks like your tag is `v3.8.9`, rather than just `3.8.9`. R10k needs you to specify the exact text of the tag to be able to find it. If you do `:tag => 'v3.8.9'`, does that work for you?

**Comment by jjarokergc** [comment]
Hello Maggie,
My apologies.  
You are correct; I didn't include the 'v' in the tag name.
Thank you for your help,
Jon
